CREATE TABLE deliberations (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  signal_id               UUID REFERENCES signals(id),
  started_at              TIMESTAMPTZ DEFAULT now(),
  bull_score              INT,
  bull_thesis             TEXT,
  bear_score              INT,
  bear_thesis             TEXT,
  bull_rebuttal           TEXT,
  bear_rebuttal           TEXT,
  quant_ev                NUMERIC,
  quant_data              JSONB,
  macro_regime            TEXT,
  macro_flag              BOOLEAN,
  sentiment_score         INT,
  sentiment_summary       TEXT,
  news_interrupt          BOOLEAN DEFAULT false,
  risk_approved           BOOLEAN,
  position_size_pct       NUMERIC,
  final_decision          TEXT,
  orchestrator_reasoning  TEXT,
  outcome                 TEXT,
  pnl_pct                 NUMERIC
);
